package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	configFileName = ".profile-manager"
)

// Config holds the profile manager configuration
type Config struct {
	ProfilesDir string `json:"profiles_dir"`
}

// GetConfigPath returns the path to the config file
func GetConfigPath() (string, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}
	return filepath.Join(homeDir, configFileName), nil
}

// LoadConfig loads the configuration from ~/.profile-manager
// Returns default config if file doesn't exist
func LoadConfig() (*Config, error) {
	configPath, err := GetConfigPath()
	if err != nil {
		return nil, err
	}

	// If config file doesn't exist, return default
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return GetDefaultConfig()
	}

	// Read config file
	content, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	// Parse simple key=value format
	config := &Config{}
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])

		switch key {
		case "profiles_dir":
			// Expand ~ in path
			config.ProfilesDir = expandPath(value)
		}
	}

	// If profiles_dir is empty, use default
	if config.ProfilesDir == "" {
		defaultConfig, err := GetDefaultConfig()
		if err != nil {
			return nil, fmt.Errorf("failed to get default config: %w", err)
		}
		config.ProfilesDir = defaultConfig.ProfilesDir
	}

	return config, nil
}

// SaveConfig saves the configuration to ~/.profile-manager
func SaveConfig(config *Config) error {
	configPath, err := GetConfigPath()
	if err != nil {
		return err
	}

	// Expand paths to use ~ notation if in home directory
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	profilesDir := config.ProfilesDir
	if strings.HasPrefix(profilesDir, homeDir) {
		profilesDir = "~" + profilesDir[len(homeDir):]
	}

	// Write config file
	content := fmt.Sprintf(`# Profile Manager Configuration
# This file is automatically generated by 'profile init'
# You can edit this file manually if needed

profiles_dir=%s
`, profilesDir)

	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// GetDefaultConfig returns the default configuration
func GetDefaultConfig() (*Config, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return nil, fmt.Errorf("failed to get home directory: %w", err)
	}

	return &Config{
		ProfilesDir: filepath.Join(homeDir, "workspaces", "profiles"),
	}, nil
}

// expandPath expands ~ and environment variables in a path
func expandPath(path string) string {
	// Expand ~
	if strings.HasPrefix(path, "~") {
		homeDir, err := os.UserHomeDir()
		if err == nil {
			path = filepath.Join(homeDir, path[1:])
		}
	}

	// Expand environment variables
	path = os.ExpandEnv(path)

	// Clean the path
	return filepath.Clean(path)
}
